pipeline {
	agent any
	stages{
		stage('Build'){
			steps{
				echo "Build"	
			}
		}
		stage('Test'){
			steps{
				echo "Test2"
			}
		}
		stage('Integration'){
			steps{
				echo "Integration"
			}
		}
	}
}

